### ISSUE TITLE
URL kopieren - Bild laden

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [FriendsOfREDAXO/asset_import#6]
**Feature description / Feature Beschreibung**

Wenn, recherchiere ich auch Bilder direkt auf den jeweiligen Portalen und/oder lade sie für den Print-Bereich zunächst dort runter. 

Eine URL ins Addon reinzukippen, das dann per API das Bild in hoher Auflösung abruft, wäre für mich eine Erleichterung.

**Comment by skerbis** [comment]
Der Provider für Pixabay kann das nun. Es muss jeweils beim Provider realisiert werden.
